# Настройки подключения к SQL Server
mssql:
  server: "USQL2" # Имя тестового сервера 
  port: 1433
  user: "sa" # Имя пользователя SQL [cite: 5]
  password: "Jc/x2no@" # Пароль SQL [cite: 5]
  # Путь для перемещения файлов данных/логов при восстановлении
  restore_path: "/var/opt/mssql/data" # Указанный каталог

# Настройки доступа к Windows-шаре (для бэкапов)
smb_share:
  remote_path: "//veeamsrv.kcep.local/backup$/mssql" # Удаленный путь к шаре [cite: 3]
  local_mount_point: "/mnt/sql_backups" # Локальная точка монтирования [cite: 11]
  domain: "kcep" # Доменная часть логина [cite: 5]
  user: "sql" # Логин для шары [cite: 5]
  password: "sql" # Пароль для шары [cite: 5]

# Настройки приложения и безопасности
app:
  bind_address: "0.0.0.0:8080"
  log_file: "/var/log/sqlmanager/sqlmanager.log" # Путь к файлу логов [cite: 15]
  log_level: "DEBUG" # Уровень логирования (INFO, ERROR, DEBUG) [cite: 17]
  backup_blacklist: # Черный список бэкапов
    - "-=NoUsedBaseBackups=-"
    - "-=scripts=-"
    - "-=SQL1=-"
    - "autojournal"
    - "Forbest_test"
    - "FullBackupBases"
    - "Kazcentrelektroprvod2010"
    - "master-mssql"
    - "master-nsql"
    - "master-usql"
    - "master-wms"
    - "msdb-mssql"
    - "msdb-nsql"
    - "msdb-usql"
    - "msdb-wms"
    - "test"
    - "test_upp"
    - "test_upp_forbitrix24"
    - "wms"

# Белый список IP-адресов/хостов для доступа к веб-интерфейсу 
whitelist:
  - "127.0.0.1"
  - "10.10.100.40"
  - "10.10.100.49"
  - "10.10.102.122"
  - "10.10.102.184"
  - "10.10.100.56"

