# Настройки подключения к SQL Server
mssql:
  server: "USQL2" # Имя тестового сервера 
  port: 1433
  user: "sa" # Имя пользователя SQL
  password: "Jc/x2no@" # Пароль SQL
  # Путь для перемещения файлов данных/логов при восстановлении
  restore_path: "/var/opt/mssql/data" # Указанный каталог

# Настройки доступа к Windows-шаре (для бэкапов)
smb_share:
  remote_path: "//veeamsrv.kcep.local/backup$/mssql" # Удаленный путь к шаре
  local_mount_point: "/mnt/sql_backups" # Локальная точка монтирования

# Настройки приложения и безопасности
app:
  bind_address: "0.0.0.0:8088"
  log_file: "/var/log/sqlmanager/sqlmanager.log" # Путь к файлу логов
  log_level: "DEBUG" # Уровень логирования (INFO, ERROR, DEBUG)
  backup_blacklist: # Черный список бэкапов
    - "-=NoUsedBaseBackups=-"
    - "-=scripts=-"
    - "-=SQL1=-"
    - "autojournal"
    - "Forbest_test"
    - "FullBackupBases"
    - "Kazcentrelektroprvod2010"
    - "master-mssql"
    - "master-nsql"
    - "master-usql"
    - "master-wms"
    - "msdb-mssql"
    - "msdb-nsql"
    - "msdb-usql"
    - "msdb-wms"
    - "test"
    - "test_upp"
    - "test_upp_forbitrix24"
    - "wms"

# Белый список IP-адресов/хостов для доступа к веб-интерфейсу 
whitelist:
  - "127.0.0.1"
  - "10.10.100.40"
  - "10.10.100.49"
  - "10.10.102.122"
  - "10.10.102.184"
  - "10.10.100.56"

version: 1.1.14
